"""empty message

Revision ID: 5a496ce1131d
Revises: 
Create Date: 2024-12-30 21:04:20.001589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a496ce1131d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index('ix_content_Module')
        batch_op.create_index(batch_op.f('ix_content_Module'), ['Module'], unique=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('announcement', sa.Boolean(), nullable=True, default=False))

    op.execute("""
    UPDATE notifications
    SET announcement = anoncement
    WHERE anoncement IS NOT NULL;
    """)

    # Drop the 'anoncement' column after migration
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('anoncement')

    # You can also replace any instance of 'anoncement' with 'announcement' if necessary.
    op.execute("""
                UPDATE user
                SET web_notif = json_set(web_notif, '$.announcement', json_extract(web_notif, '$.anoncement'))
                WHERE web_notif IS NOT NULL AND json_extract(web_notif, '$.anoncement') IS NOT NULL;
                """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anoncement', sa.BOOLEAN(), nullable=True, default=False))
        batch_op.drop_column('announcement')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_Module'))
        batch_op.create_index('ix_content_Module', ['Module'], unique=False)

    op.execute("""
    UPDATE notifications
    SET anoncement = announcement
    WHERE announcement IS NOT NULL;
    """)

    op.execute("""
    UPDATE user
    SET web_notif = json_set(web_notif, '$.anoncement', json_extract(web_notif, '$.announcement'))
    WHERE web_notif IS NOT NULL AND json_extract(web_notif, '$.announcement') IS NOT NULL;
    """)

    # ### end Alembic commands ###
